<?php
/**
 * @file
 * commerce_digital_only_text.module
 * Fixes an issue with /store page where the product options dropdown doesn't 
 * show if printed editions are disabled.
 */

/**
 * Implements hook_help().
 */
function commerce_digital_only_text_help($path, $arg) {
  switch ($path) {
    case 'admin/help#commerce_digital_only_text':
      return t("Fixes an issue with /store page where the product options 
        dropdown doesn't show if printed editions are disabled.");
  }
}

/**
 * Implements hook_form_alter().
 */
function commerce_digital_only_text_form_alter(&$form, &$form_state, $form_id) {
  if (strpos($form_id, 'commerce_cart_add_to_cart_form') === 0) {
    // Este número sólo está disponible en edición digital.
    $message = t('This issue is available as digital edition only.');

    // If the attributes element of the array is missing, we know that the
    // dropdown list will be missing on the screen.
    if (!isset($form['attributes'])) {
      $form['commerce_digital_only_text'] = array(
        '#markup' => '<strong>' . $message . '</strong>',
      );
    }
  }
}
