<?php
function redirect_domain_boot(){
  // Note that when hook_boot is called, drupal goto is not definied, hence we 
  // are using the following method instead: 
  // header("Location: http://www.example.com/");exit; 
  $host = $_SERVER['HTTP_HOST'];
  
  // If the host is www.danzaeuropa.net, we want to go to 
  // wwww.danceeurope.net/es
  if ($host == 'www.danzaeuropa.net') {
    header("Location: http://www.danceeurope.net/es");
    exit;
  }
}
