<?php
function redirect_domain_boot(){
  //Note that when hook_boot is called, drupal goto is not definied, hence we are using the following method instead: heaader("Location: http://www.example.com/");exit; 
  /*
  $danceeurope_net = 'www.danceeurope.net';

  $danzaeuropa_net = 'www.danzaeuropa.net';
  $danzaeuropa_net_start = 'es';
   */
  $host = $_SERVER['HTTP_HOST'];
  $uri = $_SERVER['REQUEST_URI'];

  $uri_parts=explode('/', $uri);
  $uri_start=$uri_parts[1];
  
  // If we are at '/' on the danzaeuropa.net home page, we want to go to 
  // danceeurope.net/es
  if ($host == 'www.danzaeuropa.net' AND $uri=="/") {
    header("Location: http://www.danceeurope.net/es");
    exit;
  }
  /*
  //Else if the first part of the URI is lqpt and we are not on the lqpt domain, the we should redirect to lqpt domain
  elseif($uri_start==$lqpt_start AND $host!=$lqpt_host ){
    header("Location: http://{$lqpt_host}{$uri}");
    exit;
  }
  //Else if the first part of the URI is not lqpt and we are not on the lq domain then we should redirect to the lq domain
  elseif($uri_start!=$lqpt_start AND $host!=$lq_host ){
    header("Location: http://{$lq_host}{$uri}");
    exit;
  }
   */
}
