<?php
/**
 * Implements hook_form_alter().
 *
 * Provides some defaults for bulk product creation
 */
function bulk_product_creation_defaults_form_commerce_bpc_create_bulk_form_alter(&$form, &$form_state, $form_id) {
  // TODO: This should be user-configurable
  $product_name = "de-en";
  // Maybe we could get the price from the last product (sku=issue-000-digital)
  $default_price = '3.95';
  $default_price_eur = '5.50';
  // TODO: Month and year blank while entering legacy data
  //$month = date('F');
  $month = '';
  //$year = date('Y');
  $year = '';
  // get latest magazine issue number
  $issue_number = '000';
  $query = new EntityFieldQuery();
  $query
    ->entityCondition('entity_type', 'commerce_product')
    ->entityCondition('bundle', 'product')
    ->propertyOrderBy('created', 'DESC')
    ->range(0, 1); // return first result only
  $result = $query->execute();

  // We are only expecting one product, but entity_load gives us an array
  // (which we expect will only have one element).
  $products = entity_load('commerce_product', array_keys($result['commerce_product']));
  foreach ($products as $product) {
    $sku = $product->sku;
    // We are expecting something like:
    // de-en-17-digital-eu
    $sku_parts = explode('-', $sku);
    if (isset($sku_parts[2])) {
      if (is_numeric($sku_parts[2])) {
        $next_number = $sku_parts[2] + 1;
        $issue_number = sprintf("%03d", $next_number);
      }
    }
  }
  $form['product']['sku_fragment']['#default_value'] = "$product_name-$issue_number";
  $form['product']['commerce_price']['und']['0']['amount']['#default_value'] = $default_price;
  $form['product']['commerce_price_gbp']['und']['0']['amount']['#default_value'] = $default_price;
  $form['product']['commerce_price_eur']['und']['0']['amount']['#default_value'] = $default_price_eur;
  $form['product']['title_fragment']['#default_value'] = "Issue #$issue_number $month $year";
  $form['combinations']['field_product_options']['und']['#default_value'] = array('digital', 'print', 'combo');
  $form['combinations']['field_postal_delivery']['und']['#default_value'] = array('uk', 'eu', 'world');
  $form['submit']['#disabled'] = TRUE;
}

